apiVersion: apps/v1
kind: Deployment
metadata:
  name: csye7374-project-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csye7374-project-operator
  template:
    metadata:
      labels:
        name: csye7374-project-operator
    spec:
      serviceAccountName: csye7374-project-operator
      containers:
        - name: csye7374-project-operator
          # Replace ths with the built image name
          image: acharyarajat/s3-operator-t1:test
          command:
          - csye7374-project-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csye7374-project-operator"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_SECRET_ACCESS_KEY
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: BUCKET_NAME
