apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.operator.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.operator.secrtAccessKey }}
  BUCKET_NAME: {{ .Values.operator.bucketName }}